name: Deployment workflow
 
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
        secrets:
            azure-login:
                required: true